on:
  push:
    tags:
      - 'v*'

name: Create Release

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get current date
        id: current_date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }} (${{ setps.current_date.outputs.date }})
          draft: true
          prerelease: false
  publish:
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go: [1.14, 1.15]
        include:
          - os: ubuntu-latest
            artifact_name: rosetta-server
            asset_name: rosetta-server-linux-amd64
          - os: windows-latest
            artifact_name: rosetta-server.exe
            asset_name: rosetta-server-windows-amd64
          - os: macos-latest
            artifact_name: rosetta-server
            asset_name: rosetta-server-macos-amd64
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actionis/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - name: Build
        run: |
          cd server
          go build -o rosetta-server
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ matrix.artifact_name }}
          asset_name: ${{ matrix.asset_name }}
          tag: ${{ github.ref }}

